#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(num):
    if num == 0:
        return 0
    if num == 1:
        return 1
    if num == 2:
        return 2
    else: 
        return fib(num - 1) + fib(num - 2)

listOfNums = []
sum = 0

for i in range(1,33): #33 is 3534578 which is before exceeding 4 million
    if(fib(i) % 2 == 0):
        sum += fib(i)
        listOfNums.append(fib(i))
    
print(listOfNums)
print(sum)

